# Generated by Django 2.2.7 on 2020-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='type',
            field=models.CharField(blank=True, default='move', max_length=30),
        ),
    ]
