# Generated by Django 2.2.7 on 2020-02-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_change_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='born',
            name='change',
        ),
        migrations.RemoveField(
            model_name='die',
            name='change',
        ),
        migrations.RemoveField(
            model_name='history',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='move',
            name='change',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='change',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='change',
        ),
        migrations.DeleteModel(
            name='Change',
        ),
    ]
