# Generated by Django 2.2.7 on 2020-02-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20191202_1058'),
        ('history', '0003_auto_20200218_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_weight', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=300)),
                ('partner', models.CharField(default='', max_length=50)),
                ('animals', models.ManyToManyField(blank=True, null=True, to='info.Animal')),
                ('from_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_moves_from', to='info.Cell')),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.History')),
                ('to_cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_moves_to', to='info.Cell')),
            ],
        ),
        migrations.RemoveField(
            model_name='die',
            name='from_cell',
        ),
        migrations.RemoveField(
            model_name='move',
            name='from_cell',
        ),
        migrations.RemoveField(
            model_name='move',
            name='to_cell',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='to_cell',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='from_cell',
        ),
        migrations.DeleteModel(
            name='Born',
        ),
        migrations.DeleteModel(
            name='Die',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
