# Generated by Django 2.2.7 on 2020-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='partner',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
