# Generated by Django 2.2.7 on 2019-11-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfBarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='откорм', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='взрослые', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Старт', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TypeOfFood')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('date_of_last_reweighting', models.DateField()),
                ('last_reweighting', models.FloatField(default=0)),
                ('date_of_last_wash', models.DateField()),
                ('barn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Barn')),
                ('trough', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Trough')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TypeOfCell')),
            ],
        ),
        migrations.AddField(
            model_name='barn',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TypeOfBarn'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=20)),
                ('number_of_group', models.CharField(default='', max_length=20)),
                ('number_of_mother', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField()),
                ('weight_of_birth', models.FloatField(default=0)),
                ('special_marks', models.CharField(default='', max_length=300)),
                ('approximately_date_of_delivery', models.DateField()),
                ('date_of_delivery', models.DateField()),
                ('last_weight', models.FloatField(default=0)),
                ('date_of_last_reweighting', models.DateField()),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Cell')),
                ('lovely_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TypeOfFood')),
            ],
        ),
    ]
