# Generated by Django 2.2.7 on 2019-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_last_reweighting',
            field=models.DateField(auto_now=True),
        ),
    ]
