# Generated by Django 2.2.7 on 2019-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191125_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='trough',
            name='date_of_last_feeding',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='approximately_date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='date_of_last_reweighting',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='date_of_last_wash',
            field=models.DateField(auto_now=True),
        ),
    ]
